### ISSUE TITLE
Highlight overdue projects as red bars

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/project-manager#23]
In the projectsTimeLineChart module visualize overdue projects as red bars. Overdue means older than 12 weeks, for example. The overdue time can be changed from time to time or adapted by project managers, so make it dynamic ;)

**Comment by julianspaeth** [comment]
Da gab es jetzt mehere möglichkeiten und das mit dem Bars einfärben ist auch etwas tricky das dynimisch hinzukriegen. Ich habe es jetzt so gemacht:

 Die 4. (also letzte) Bar wird immer rot dargestellt. Später könnte man dann eben die Zahl dynamisch ändern z.B. von 12 auf 15 und das könnte dann alles angepasst werden (muss ja dann auch aus der Datenbank schon so ausgelesen werden). Der letzte Balken zeigt somit aber immer die overdue Projekte in rot an, es ändert sich dann nur der Text der Spalte (> 15 weeks) und gegebenenfalls der Text der 3. Spalte (6 to 15 weeks. Ist das in Ordnung so? 

Wo wird die overdue time dann später festgelegt? Oder muss ich dafür noch etwas direkt in den Project Manager einbauen?
