### ISSUE TITLE
Fix Query

### ISSUE THREAD

**Issue by julianspaeth** [qbicsoftware/project-manager#44]
What is queried for columns "Report sent" and 'Data analyzed'? For example for project QIRCS there are 3 reports visible in the portal and it says empty field here.

**Comment by julianspaeth** [comment]
I think the user has to set those values by hand.

**Comment by subwaystation** [comment]
@qbicStefanC

**Comment by julianspaeth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project Manager: Fix bugs](https://trello.com/c/I2OQr5Bf/86-project-manager-fix-bugs)
